server:
  port: 1234
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: bapunhimanshu08@gmail.com
    password: 995bapun
    properties.mail.smtp:
                      auth: ture
                      starttls:
                         enable: true      
  